version: 0.1

phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 16
  pre_build:  
    commands:
      - echo Installing Dependencies
      - npm install
      - ${aws ecr get-login --no-included-email --region $AWS_DEFAULT_REGION}
  build:
    commands:
      - echo building docker image
      - docker build -t $IMAGE_REPO_NAME:$IMAGE-TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE-TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE-TAG
  post_build:
    commands:
      - echo pushing the docker image
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE-TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE-TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
