version: 0.2

phases:
  pre_build:  
    commands:
      - echo Installing Dependencies
      - npm install
  build:
    commands:
      - echo building docker image dockertrial:latest
      - docker build -t dockertrial:latest .
      - docker tag dockertrial:latest 709658483072.dkr.ecr.us-east-1.amazonaws.com/dockertrial:latest
  post_build:
    commands:
      - echo pushing the docker image
      - docker push 709658483072.dkr.ecr.us-east-1.amazonaws.com/dockertrial:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' dockertrial 709658483072.dkr.ecr.us-east-1.amazonaws.com/dockertrial:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
  
    
    
