version: 0.2

phases:
  install:
      runtime-versions:
        nodejs: 12
  pre_build:
    commands:
      - echo installing packages
      - npm install
  build:
    commands:
      - echo test started on `date` 
      - npm test
      
      
reports:
  jest_reports:
          files: 
            - **/*
          file-format: JUNITXML
          base-directory: "reports"
